// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjNph6H9WEoruen2j4Z3uaY_i375eu80s',
    appId: '1:479868314043:web:4da624dc36054500dda49e',
    messagingSenderId: '479868314043',
    projectId: 'fruithub-app-4d245',
    authDomain: 'fruithub-app-4d245.firebaseapp.com',
    storageBucket: 'fruithub-app-4d245.firebasestorage.app',
    measurementId: 'G-LGE6967SE3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKQbb0lO6g2kJXHpwH3NIoiRwBsldRuEc',
    appId: '1:479868314043:android:0a35fc3650f04193dda49e',
    messagingSenderId: '479868314043',
    projectId: 'fruithub-app-4d245',
    storageBucket: 'fruithub-app-4d245.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZ8RPfPTL8q6_IysZVhyuA3IrojQ1KTWE',
    appId: '1:479868314043:ios:55e128b02e54cae3dda49e',
    messagingSenderId: '479868314043',
    projectId: 'fruithub-app-4d245',
    storageBucket: 'fruithub-app-4d245.firebasestorage.app',
    androidClientId: '479868314043-5icghie2anvlahbpit96kr5fqqcgh572.apps.googleusercontent.com',
    iosClientId: '479868314043-307h0rikn1p4ra50g2moa81uhfbp2dnn.apps.googleusercontent.com',
    iosBundleId: 'com.example.fruitHubDashboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZ8RPfPTL8q6_IysZVhyuA3IrojQ1KTWE',
    appId: '1:479868314043:ios:55e128b02e54cae3dda49e',
    messagingSenderId: '479868314043',
    projectId: 'fruithub-app-4d245',
    storageBucket: 'fruithub-app-4d245.firebasestorage.app',
    androidClientId: '479868314043-5icghie2anvlahbpit96kr5fqqcgh572.apps.googleusercontent.com',
    iosClientId: '479868314043-307h0rikn1p4ra50g2moa81uhfbp2dnn.apps.googleusercontent.com',
    iosBundleId: 'com.example.fruitHubDashboard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjNph6H9WEoruen2j4Z3uaY_i375eu80s',
    appId: '1:479868314043:web:e326fd8431cbe1e2dda49e',
    messagingSenderId: '479868314043',
    projectId: 'fruithub-app-4d245',
    authDomain: 'fruithub-app-4d245.firebaseapp.com',
    storageBucket: 'fruithub-app-4d245.firebasestorage.app',
    measurementId: 'G-4PTGY7BG64',
  );
}
